version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    volumes:
      - .:/src
