# Generated by Django 3.2.3 on 2021-05-28 15:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210529_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_post_path),
        ),
    ]
