# Generated by Django 3.2.3 on 2021-05-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile_image',
            new_name='post_image',
        ),
    ]
