# Generated by Django 3.2.3 on 2021-05-30 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_profile_image_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_users',
            field=models.ManyToManyField(blank=True, related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=1000)),
                ('stars', models.PositiveSmallIntegerField()),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_post', to='api.post')),
            ],
        ),
    ]
