# Generated by Django 3.2.3 on 2021-05-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(choices=[('東京都', 'Tokyo'), ('千葉県', 'Chiba')], default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
