# Generated by Django 3.2.3 on 2021-05-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210530_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(choices=[('東京都', 'Tokyo'), ('千葉県', 'Chiba')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
