# Generated by Django 3.2.3 on 2021-05-30 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210530_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_user', to='api.user'),
            preserve_default=False,
        ),
    ]
