# Generated by Django 3.2.3 on 2021-05-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210530_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_address',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='selected_address', to='api.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_gender',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='selected_gender', to='api.gender'),
            preserve_default=False,
        ),
    ]
