# Generated by Django 3.2.3 on 2021-06-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210607_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission_format',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='club_activities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='undergraduate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
