# Generated by Django 3.2.3 on 2021-06-09 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210608_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following_users',
            field=models.ManyToManyField(blank=True, default=[], related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, default=[], related_name='tags', to='api.Tag'),
        ),
    ]
