# Generated by Django 3.2.3 on 2021-06-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_profile_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='problem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='want_hear',
            field=models.CharField(default='', max_length=100),
        ),
    ]
