# Generated by Django 3.2.3 on 2021-06-11 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210611_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='message',
            name='talk_room',
        ),
        migrations.RemoveField(
            model_name='talkroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='talkroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='message',
            name='talking_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='talking_room', to='api.talkroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='entry_talk_rooms',
            field=models.ManyToManyField(blank=True, default=[], related_name='entry_talk_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talkroom',
            name='talk_room_description',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_room', to='api.talkroom')),
                ('join_users', models.ManyToManyField(blank=True, default=[], related_name='join_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
