# Generated by Django 3.2.3 on 2021-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210611_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkroom',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
