# Generated by Django 3.2.3 on 2021-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_talkroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
