# Generated by Django 3.2.4 on 2021-06-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210622_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_user',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_author', to='api.user'),
            preserve_default=False,
        ),
    ]
