# Generated by Django 3.2.4 on 2021-06-22 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210622_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkroom',
            name='join_users',
        ),
        migrations.AddField(
            model_name='talkroom',
            name='opponent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
