# Generated by Django 3.2.4 on 2021-06-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210622_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_text',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_address', to='api.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_gender', to='api.gender'),
        ),
    ]
