# Generated by Django 3.2.4 on 2021-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_profile_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkroom',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
